---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  labels:
    app: glossary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glossary
        component: config
    #      annotations:
    #        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: config
        image: solomkinmv/config-server
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "native"
        ports:
        - containerPort: 8888
        #        todo: should be UP without Eureka
        #        livenessProbe:
        #          initialDelaySeconds: 15
        #          periodSeconds: 15
        #          httpGet:
        #            path: /actuator/health
        #            port: 8888
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: glossary
spec:
  ports:
  - nodePort: 30888
    port: 8888
  selector:
    app: glossary
    component: config
  type: NodePort