---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  labels:
    app: glossary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glossary
        component: config
    spec:
      containers:
      - name: config
        image: solomkinmv/config-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            path: /actuator/health
            port: 8888
        resources:
          limits:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: glossary
spec:
  ports:
  - nodePort: 30888
    port: 8888
  selector:
    app: glossary
    component: config
  type: NodePort