---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-service
  labels:
    app: glossary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glossary
        component: statistics-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
      - name: statistics-service
        image: solomkinmv/statistics-service
        imagePullPolicy: Always
        env:
        # Due to camelcase issues with "preferIpAddress", _JAVA_OPTIONS is used here
        - name: _JAVA_OPTIONS
          value: -Deureka.instance.preferIpAddress=true
        ports:
        - containerPort: 8086
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            path: /actuator/health
            port: 8086
        resources:
          requests:
            memory: 256Mi
            cpu: 0.1
          limits:
            memory: 512Mi
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    app: glossary
spec:
  ports:
  - port: 8086
    nodePort: 30886
  selector:
    app: glossary
    component: statistics-service
  type: NodePort
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: statistics-service
  labels:
    app: glossary
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: statistics-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 1000Mi
  - type: Pods
    pods:
      metricName: rabbitmq_queue_size
      targetAverageValue: 10