version: '3.5'

services:
  config:
    environment:
      SPRING_PROFILES_ACTIVE: native
    image: solomkinmv/config-server
    restart: always
    ports:
    - 8888:8888
    depends_on:
    - rabbitmq
    - keycloak
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: solomkinmv/discovery-server
    restart: always
    depends_on:
    - config
    - rabbitmq
    ports:
    - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: solomkinmv/gateway
    env_file:
    - principal_keys.env
    restart: always
    depends_on:
    - config
    - keycloak
    - rabbitmq
    ports:
    - 8008:8008
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  storage-service:
    image: solomkinmv/storage-service
    restart: always
    depends_on:
    - config
    - keycloak
    - rabbitmq
    ports:
    - 8081:8081
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  translate-service:
    image: solomkinmv/translate-service
    env_file:
    - principal_keys.env
    restart: always
    depends_on:
    - config
    - keycloak
    - rabbitmq
    ports:
    - 8082:8082
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  tts-service:
    image: solomkinmv/tts-service
    env_file:
    - principal_keys.env
    restart: always
    depends_on:
    - config
    - keycloak
    - rabbitmq
    ports:
    - 8083:8083
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  image-service:
    image: solomkinmv/image-service
    env_file:
    - principal_keys.env
    restart: always
    depends_on:
    - config
    - keycloak
    - rabbitmq
    ports:
    - 8084:8084
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  words-service-mariadb:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
    - MYSQL_ROOT_PASSWORD=p4SSW0rd
    - MYSQL_DATABASE=words-service-db
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss
    ports:
    - 3306:3306

  words-service:
    image: solomkinmv/words-service
    environment:
    - DATABASE_HOST=words-service-mariadb
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbp4ss
    - DATABASE_NAME=words-service-db
    - DATABASE_PORT=3306
    restart: always
    depends_on:
    - words-service-mariadb
    - tts-service
    - config
    - rabbitmq
    ports:
    - 8085:8085
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  keycloak:
    image: jboss/keycloak:4.1.0.Final
    ports:
    - "8000:8080"
    - "8001:9990"
    environment:
    - KEYCLOAK_LOGLEVEL=DEBUG
    - PROXY_ADDRESS_FORWARDING=true
    - KEYCLOAK_USER=keycloak
    - KEYCLOAK_PASSWORD=keycloak
    - DB_VENDOR=mysql
    - DB_ADDR=keycloak-mysql
    - DB_DATABASE=keycloak
    - DB_USER=keycloak
    - DB_PASSWORD=password
    depends_on:
    - keycloak-mysql
    command: -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak/test/realm-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
    - .:/tmp/keycloak/test/

  keycloak-mysql:
    image: mysql:5.7.22 # mysql v8 doesn't work with keycloak 4.1.0, there is some bug
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=password
    ports:
    - 3307:3306

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
    - RABBIT_ADDRESSES=rabbitmq:5672
    ports:
    # Port used for the Zipkin UI and HTTP Api
    - 9411:9411
    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672

  dashboard:
    image: solomkinmv/dashboard
    restart: always
    depends_on:
    - config
    - registry
    ports:
    - 9001:9001
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mongodb:
    image: mongo:4.0.3
    restart: always
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo_user
    - MONGO_INITDB_ROOT_PASSWORD=pswrd
    - MONGO_INITDB_DATABASE=stats