dist: trusty
sudo: required

services:
  - docker

language: java
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
script:
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew config-server:docker
  - ./gradlew config-server:dockerPush
  - ./gradlew discovery-server:docker
  - ./gradlew discovery-server:dockerPush
  - ./gradlew gateway:docker
  - ./gradlew gateway:dockerPush
  - ./gradlew storage-service:docker
  - ./gradlew storage-service:dockerPush