dist: trusty
sudo: required

services:
  - docker

language: java
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew config-server:docker
  - ./gradlew config-server:dockerPush
  - ./gradlew discovery-server:docker
  - ./gradlew discovery-server:dockerPush