version: '3.5'

services:
  config:
    environment:
      SPRING_PROFILES_ACTIVE: native
    image: solomkinmv/config-server
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: solomkinmv/discovery-server
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: solomkinmv/gateway
    restart: always
    depends_on:
      - config
    ports:
      - 8008:8008
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  storage-service:
    image: solomkinmv/storage-service
    restart: always
    depends_on:
      - config
    ports:
      - 8081:8081
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  translate-service:
    image: solomkinmv/translate-service
    env_file:
      - principal_keys.env
    restart: always
    depends_on:
      - config
    ports:
      - 8082:8082
    logging:
      options:
        max-size: "10m"
        max-file: "10"