version: '2.1'

services:
  config:
    environment:
      SPRING_PROFILES_ACTIVE: native
    image: solomkinmv/config-server
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: solomkinmv/discovery-server
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"