security.jwt:
  tokenExpirationTime: 600 # minutes
  refreshTokenExpTime: 1800 # minutes
  tokenIssuer: http://solomkinmv.github.io
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring:
  datasource.url: jdbc:h2:./db/testDb
  jpa.hibernate.ddl-auto: create

translate.key: trnsl.1.1.20170203T233533Z.93a3ca61465d0928.e64b79ae3d8a474cb87ef51e06ab926755908d76

flickr:
  key: 4e406d6e8e67b788858f2beb433d8369
  secret: a7f5e6dd0dc2389a