eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
